# this property is useful for conditional filtering of content that is separate from the PDF.
output: web

# this appears on the top navigation bar next to the home button
topnav_title: Hygames

# this appears in the html browser tab for the site title (seen mostly by search engines, not users)
site_title: Hygames

github_repo: https://github.com/hygames-team/www-hygames-co/
github_org: https://github.com/hygames-team/

github_editme_basepath: https://github.com/hygames-team/www-hygames-co/edit/master/

# google-analytics ID
google_analytics: UA-90624848-2

# these are the files and directories that jekyll will exclude from the build
exclude:
  - .idea/
  - .gitignore

# library used for syntax highlighting
highlighter: rouge

# filter used to process markdown
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

# collections are declared here. This renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true
collections:
  posts:
    output: true
    permalink: /:year/:short_month/:title/

# defaults for front matter
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      topnav: topnav
  -
    scope:
      path: "pages/gamebox"
      type: "pages"
    values:
      editme: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      tooltip: true

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      topnav: topnav

sidebars:
- gamebox_sidebar
- other